# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Check commit
        run: |
          LATEST_COMMIT_IN_PR="${{ github.event.pull_request.head.sha }}"
          echo $LATEST_COMMIT_IN_PR
          COMMIT_IN_DEVELOP=`git branch --contains $LATEST_COMMIT_IN_PR|grep develop|wc -l`
          echo "COMMIT_IN_DEVELOP=$COMMIT_IN_DEVELOP" >> $GITHUB_ENV
          echo "COMMIT_MSG_DEV=Commit $LATEST_COMMIT_IN_PR not found in develop branch :x:" >> $GITHUB_ENV

      - name: If commit in develop
        if: ${{ env.COMMIT_IN_DEVELOP > 0}}
        run: |
          echo "COMMIT_MSG_DEV=Thank you for pushing your code to the develop branch first :heavy_check_mark:" >> $GITHUB_ENV

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "${{ env.COMMIT_MSG_DEV }}"
          GITHUB_TOKEN: ${{ github.token }}

